<?php

/**
 * @file
 * Contains specbee.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function specbee_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the specbee module.
    case 'help.page.specbee':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Specbee Interview Assignment') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function specbee_theme() {
  return [
    'specbee_site_loc_time_block' => [
      'variables' => [
        'content' => NULL,
      ]
    ],
  ];
}
